# Generated by Django 5.2.11 on 2026-04-12 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Office')], default='HOME', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
