# Generated by Django 6.0.3 on 2026-04-22 07:26

import orders.models
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    OrderModel = apps.get_model('orders', 'Order')
    for row in OrderModel.objects.all():
        row.order_id = f"ORD-{__import__('uuid').uuid4().hex[:10].upper()}"
        row.save(update_fields=['order_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=50, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=50, unique=True),
        ),
    ]
